### ISSUE TITLE
Issues using xy-stich

### ISSUE THREAD

**Issue by keesj-exset** [SiliconAnalysis/xystitch#38]
Hi,

I am trying to use xy-stich to stich images that I captured with a small CNC machine of a PCB. I am having bad luck doing so. Can you please help / have a look at what is going on? (I spend a considerable amount of time trying different hugin options )

I am using a script to move the cnc and take picture and save them in a format "compatible" with xy-stich. 
https://gist.github.com/keesj-exset/4397e077a748291ddea9d70ec7520ab8

Adding a sample of the images (I have more but merging 4x4 is already quite slow)

[test4x4.zip](https://github.com/JohnDMcMaster/xystitch/files/7668013/test4x4.zip)

currently the log states
```
2021-12-07T11:22:09.345823: pr0npto starting
2021-12-07T11:22:09.345869: In: out.pto
2021-12-07T11:22:09.345894: Out: out.pto
2021-12-07T11:22:09.347551: Optimizing
2021-12-07T11:22:09.348253: Constructing image coordinate map from tagged file names...
2021-12-07T11:22:09.348277: Row / col hints insufficient, guessing row / col layout from file names
2021-12-07T11:22:09.348359: Constructing columns from set {0, 1, 2, 3}
2021-12-07T11:22:09.348380: Constructing rows from set {0, 1, 2, 3}
2021-12-07T11:22:09.348395: initial cols / X dim / width: 4, rows / Y dim / height: 4
2021-12-07T11:22:09.348483: Verbose: 0
2021-12-07T11:22:09.348631: TEMP DIR: /tmp/ts_082E93CD60481282/
2021-12-07T11:22:09.349185: working direclty on /tmp/ts_082E93CD60481282/D43DA36D098D916C.pto
2021-12-07T11:22:09.353087: Traceback (most recent call last):
2021-12-07T11:22:09.353121:   File "/usr/local/bin/xy-pto", line 4, in <module>
2021-12-07T11:22:09.353212:     __import__('pkg_resources').run_script('xystitch==1.1.0', 'xy-pto')
2021-12-07T11:22:09.353235:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
2021-12-07T11:22:09.353403:     self.require(requires)[0].run_script(script_name, ns)
2021-12-07T11:22:09.353424:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
2021-12-07T11:22:09.353684:     exec(script_code, namespace, namespace)
2021-12-07T11:22:09.353705:   File "/usr/local/lib/python3.9/dist-packages/xystitch-1.1.0-py3.9.egg/EGG-INFO/scripts/xy-pto", line 228, in <module>
2021-12-07T11:22:09.353789:   File "/usr/local/lib/python3.9/dist-packages/xystitch-1.1.0-py3.9.egg/xystitch/optimizer.py", line 1315, in run
2021-12-07T11:22:09.353910:   File "/usr/local/lib/python3.9/dist-packages/xystitch-1.1.0-py3.9.egg/xystitch/optimizer.py", line 878, in xy_opt
2021-12-07T11:22:09.353974:   File "/usr/local/lib/python3.9/dist-packages/xystitch-1.1.0-py3.9.egg/xystitch/optimizer.py", line 1099, in get_rms
2021-12-07T11:22:09.354040: ZeroDivisionError: float division by zero


```

any hints what I am doing wrong?

**Comment by JohnDMcMaster** [comment]
A few quick comments:
-Origin needs to be upper left corner. However you have r=0 c=0 in the lower right corner
-You have row and column switched
-You have high overlap between images (ex: one feature appears in 4 images within a row). panotools generally doesn't like this. I generally shoot for about 30% overlap, you have something like 75%.

So if I was going to try to stitch this set I would do this:
-swap c and r
-use rename_xy_lr.py to mirror left/right
-Remove every other image
-Most if not all of this can probably done with rename_xy.py, but I'd need to look at flags

Other: FWIW it wouldn't take much work to modify pyuscope for you application. First, it already can capture images from v4l, although would need to check your encoding for best image quality. Second, g-code is currently sent to linuxcnc, but wouldn't be hard to send it to serial port instead

**Comment by keesj-exset** [comment]
Hello,

Thank you for the review/comments. I made the necessary modifications (less overlap, corrected the row/columns) and made a new run. The results are "slightly" better as the process goes a bit further.

To get good matches  in hugin need to put a huge focal distance (e.g. 10000 mm) can I pass such option to the sticher?

(adding new capture and the improved script in the zip file)
[2ndround.zip](https://github.com/JohnDMcMaster/xystitch/files/7676410/2ndround.zip)

**Comment by JohnDMcMaster** [comment]
Quick overlap estimate:
-Step size is roughly 775 pixels in both x and y
-Image is 2048 x 1536
-X step size: 775 / 2048 = 38%
-Y step size: 775 / 1536 = 50%
-Enblend has issues with step sizes below (or near) 50% as its designed to blend two image seams together, but you've given it  three images. This may cause enblend to crash
-A healthy step size is typically around 70% (ie 30% overlap)

if you really wanted to try stitching anyway, this is the magic incantation you'd need:

```
XY_STEP_FRAC_X=0.38 XY_STEP_FRAC_Y=0.50 xy-feature out.pto *.jpg
```

Full log showing commands if you want to give it a try: https://gist.github.com/JohnDMcMaster/faae194ca7db34485252939bd16793ae

**Comment by JohnDMcMaster** [comment]
![out](https://user-images.githubusercontent.com/222171/145926659-5144959e-54cb-472c-a8da-beea238f2796.jpg)

**Comment by JohnDMcMaster** [comment]
I believe this is solved, but please let me know if otherwise
